NguyenDuyKhanh_211202428_De_1/NguyenDuyKhanh_211202428_De_1/ViewComponents/RenderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NguyenDuyKhanh_211202428_De_1.Models;

namespace NguyenDuyKhanh_211202428_De_1.ViewComponents
{
    public class RenderViewComponent: ViewComponent
    {
        private readonly OnlineShopContext db;
        private List<Category> categories;

        public RenderViewComponent(OnlineShopContext _db)
        {
            this.db = _db;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            categories = db.Categories.ToList();
            return View("Nav", categories);
        }
    }
}

NguyenDuyKhanh_211202428_De_1/NguyenDuyKhanh_211202428_De_1/Views/Shared/NguyenDuyKhanh_Footer.cshtml
<div class="footer">
	<div class="container">
		<div class="w3_footer_grids">
			<div class="col-md-3 w3_footer_grid">
				<h3>Contact</h3>

				<ul class="address">

					<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
					<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>+1234 567 567</li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Information</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="about.html">About Us</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="contact.html">Contact Us</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="short-codes.html">Short Codes</a></li>

				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Category</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="groceries.html">Groceries</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="household.html">Household</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="personalcare.html">Personal Care</a></li>

				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Profile</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="products.html">Store</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="checkout.html">My Cart</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="login.html">Login</a></li>

				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>



</div>
<div class="footer-botm">
	<div class="container">
		<div class="w3layouts-foot">
			<ul>
				<li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#" class="agile_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#" class="w3_agile_vimeo"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
			</ul>
		</div>
		<div class="payment-w3ls">
			<img src="images/card.png" alt=" " class="img-responsive">
		</div>
		<div class="clearfix"> </div>
	</div>
</div>

NguyenDuyKhanh_211202428_De_1/NguyenDuyKhanh_211202428_De_1/Views/Shared/NguyenDuyKhanh_Header.cshtml
<div class="agileits_header">
	<div class="container">
		<div class="w3l_offers">
			<p>SALE UP TO 70% OFF. USE CODE "SALE70%" . <a href="products.html">SHOP NOW</a></p>
		</div>
		<div class="agile-login">
			<ul>
				<li><a href="registered.html"> Create Account </a></li>
				<li><a href="login.html">Login</a></li>
				<li><a href="contact.html">Help</a></li>

			</ul>
		</div>
		<div class="product_list_header">
			<form action="#" method="post" class="last">
				<input type="hidden" name="cmd" value="_cart">
				<input type="hidden" name="display" value="1">
				<button class="w3view-cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
			</form>
		</div>
		<div class="clearfix"> </div>
	</div>
</div>

<div class="logo_products">
	<div class="container">
		<div class="w3ls_logo_products_left1">
			<ul class="phone_email">
				<li><i class="fa fa-phone" aria-hidden="true"></i>Order online or call us : (+0123) 234 567</li>

			</ul>
		</div>
		<div class="w3ls_logo_products_left">
			<h1><a href="index.html">super Market</a></h1>
		</div>
		<div class="w3l_search">
			<input type="search" name="Search" placeholder="Search for a Product..." required="">
			<button type="submit" class="btn btn-default search" aria-label="Left Align">
				<i class="fa fa-search" aria-hidden="true"> </i>
			</button>
			<div class="clearfix"></div>
		</div>

		<div class="clearfix"> </div>
	</div>
</div>

NguyenDuyKhanh_211202428_De_1/NguyenDuyKhanh_211202428_De_1/Views/Shared/NguyenDuyKhanh_Layout.cshtml
<!--
author: W3layouts
author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title>Online Shopping</title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- //for-mobile-apps -->
    <link href="~/NguyenDuyKhanh_211202428_De_01/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/NguyenDuyKhanh_211202428_De_01/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- font-awesome icons -->
    <link href="~/NguyenDuyKhanh_211202428_De_01/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome icons -->
    <!-- js -->
    <script src="~/NguyenDuyKhanh_211202428_De_01/js/jquery-1.11.1.min.js"></script>
    <!-- //js -->
</head>

<body>
    <!-- header -->
    <partial name="NguyenDuyKhanh_Header"/>

    <!-- //header -->
    <!-- navigation -->
    @* <partial name="NguyenDuyKhanh_Nav"/> *@
    @await Component.InvokeAsync("Render")
    <!-- //navigation -->
    @RenderBody()
    <!-- footer -->
    <partial name="NguyenDuyKhanh_Footer" />
    <!-- //footer -->
</body>
</html>

NguyenDuyKhanh_211202428_De_1/NguyenDuyKhanh_211202428_De_1/Views/Shared/NguyenDuyKhanh_Main.cshtml
<!--brands-->
<div class="brands">
    <div class="container">
        <h3>Brand Store</h3>
        <div class="brands-agile">
            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="#">Lorem</a></p>
                </div>
            </div>
            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="#">Lorem</a></p>
                </div>
            </div>
            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="#">Lorem</a></p>
                </div>
            </div>

            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="#">Lorem</a></p>
                </div>
            </div>
            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="#">Lorem</a></p>
                </div>
            </div>
            <div class="col-md-2 w3layouts-brand">
                <div class="brands-w3l">
                    <p><a href="#">Lorem</a></p>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!--//brands-->
@using NguyenDuyKhanh_211202428_De_1.Models;

@{
    Layout = "~/Views/Shared/NguyenDuyKhanh_Layout.cshtml";
}


@model List<Product>


<!-- main content -->
<div class="newproducts-w3agile">
    <div class="container">
        <h3>New offers</h3>
        <div class="agile_top_brands_grids">
            @foreach (var product in Model)
            {
                <div class="col-md-3 top_brand_left-1">
                    <div class="hover14 column">
                        <div class="agile_top_brand_left_grid">
                            <div class="agile_top_brand_left_grid_pos">
                                <img src="~/NguyenDuyKhanh_211202428_De_01//images//offer.png" alt=" " class="img-responsive">
                            </div>
                            <div class="agile_top_brand_left_grid1">
                                <figure>
                                    <div class="snipcart-item block">
                                        <div class="snipcart-thumb">
                                            <a href="products.html"><img title=" " alt=" " src="~/NguyenDuyKhanh_211202428_De_01/images/@product.Image"></a>
                                            <p>@product.Name</p>
                                            <div class="stars">
                                                <i class="fa fa-star blue-star" aria-hidden="true"></i>
                                                <i class="fa fa-star blue-star" aria-hidden="true"></i>
                                                <i class="fa fa-star blue-star" aria-hidden="true"></i>
                                                <i class="fa fa-star blue-star" aria-hidden="true"></i>
                                                <i class="fa fa-star gray-star" aria-hidden="true"></i>
                                            </div>
                                            <h4>$@product.UnitPrice <span>$@product.Available</span></h4>
                                        </div>
                                        <div class="snipcart-details top_brand_home_details">
                                            <form action="#" method="post">
                                                <fieldset>
                                                    <input type="hidden" name="cmd" value="_cart">
                                                    <input type="hidden" name="add" value="1">
                                                    <input type="hidden" name="business" value=" ">
                                                    <input type="hidden" name="item_name" value="Fortune Sunflower Oil">
                                                    <input type="hidden" name="amount" value="35.99">
                                                    <input type="hidden" name="discount_amount" value="1.00">
                                                    <input type="hidden" name="currency_code" value="USD">
                                                    <input type="hidden" name="return" value=" ">
                                                    <input type="hidden" name="cancel_return" value=" ">
                                                    <input type="submit" name="submit" value="Add to cart" class="button">
                                                </fieldset>
                                            </form>
                                        </div>
                                    </div>
                                </figure>
                            </div>
                        </div>
                    </div>
                </div>
            }
            <div class="clearfix"> </div>
        </div>
        <ul class="pagination">
            @for (int i = 1; i <= ViewBag.pageNum; i++)
            {
                <li class="page-item" page="@i">
                    @(ViewBag.categoryId != null ? "id=" + ViewBag.categoryId : "")
                    @(ViewBag.keyword != null ? "keyword=" + ViewBag.keyword : "")
                    <a class="page-link">@i</a>
                </li>
            }
        </ul>
    </div>
</div>
<!-- //main content -->


<script>
    $("body").on("click", ".page-item", function (e) {
        var page = $(this).attr("page");
        var id = $(this).attr("id");
        console.log(id)
        $.ajax({
            url: "/BaiThi/filter",
            data: {
                categoryId: id,
                page: page,

            },
            success: function (response) {
                //console.log($(response).find(".agile_top_brands_grids").html())
                $(".agile_top_brands_grids").html($(response).find(".agile_top_brands_grids").html());
            }
        })
    })


    $("li").click(function (event) {
        var page = $(this).attr("page");
        var id = $(this).attr("id");

        $.ajax({
            url: "/BaiThi",
            data: {
                categoryid: id,
                page: page,
            },
            success: function (response) {
                console.log($(response).find(".agile_top_brands_grids").html())
                $(".agile_top_brands_grids").html($(response).find(".agile_top_brands_grids").html());
            }

        })

    })
</script>

NguyenDuyKhanh_211202428_De_1/NguyenDuyKhanh_211202428_De_1/Views/Shared/NguyenDuyKhanh_Nav.cshtml
<div class="navigation-agileits">
	<div class="container">
		<nav class="navbar navbar-default">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header nav_2">
				<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
				<ul class="nav navbar-nav">
					<li class="active"><a href="index.html" class="act">Home</a></li>
					<!-- Mega Menu -->
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Groceries<b class="caret"></b></a>
						<ul class="dropdown-menu multi-column columns-3">
							<div class="row">
								<div class="multi-gd-img">
									<ul class="multi-column-dropdown">
										<h6>All Groceries</h6>
										
									</ul>
								</div>

							</div>
						</ul>
					</li>

					<li><a href="gourmet.html">Gourmet</a></li>
					<li><a href="offers.html">Offers</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</div>
		</nav>
	</div>
</div>

NguyenDuyKhanh_211202428_De_1/NguyenDuyKhanh_211202428_De_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NguyenDuyKhanh_211202428_De_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NguyenDuyKhanh_211202428_De_1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NguyenDuyKhanh_211202428_De_1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NguyenDuyKhanh_211202428_De_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>